# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["smart", "tables"]

kramdown: 
  input: GFM

# Permalinks
relative_permalinks: false
permalink: news/:title/

# Collections
collections:


# Setup
title:            'Electrical Age'
description:      'Minecraft mod - Codename : ELN'
url:              http://electrical-age.github.io
baseurl:          /

author:
  name:           'Christopher Métrailler'
  url:            http://electrical-age.net/

# Custom vars
last_version:	  1.10_r50

github:
  repo:           https://github.com/Electrical-Age/electrical-age.github.io